### PR TITLE
Add log entry for ProofState (v2)

### LINKED ISSUE #1358: Log entries for proof states
`transitionRule` should emit an `Entry` for each `ProofState`.

### PR DESCRIPTION
**Pull request by ana-pantilie**
Fixes #1358

Also fixes:
- determining the sorts in `onePathRuleToTerm`/`allPathRuleToTerm`
- forces main thread to wait for logging to finish (introduced in https://github.com/kframework/kore/pull/1387)

---

###### Reviewer checklist

- [ ] Test coverage: `stack test --coverage`
- [ ] Public API documentation: `stack haddock`

### CODE REVIEW

File: kore/test/Test/Kore/Strategies/AllPath/AllPath.hs [hunk 1]
```diff
@@ -381,15 +381,96 @@ instance Debug (Goal.Rule Goal)
 
 instance Diff (Goal.Rule Goal)
 
+transitionRuleTemplate
```
Comment (virgil-serbanuta) [inline kore/test/Test/Kore/Strategies/AllPath/AllPath.hs]: Why does the function with the same name in `Goal.hs` log transition information, while this one doesn't?

Comment (ana-pantilie) [reply kore/test/Test/Kore/Strategies/AllPath/AllPath.hs]: @virgil-serbanuta This was my original problem, that the `Goal` type for these tests does not implement `ToRulePattern`, and since logging depends on this representation we need separate `transitionRuleTemplate`s for those `goal`s which are `ToRulePattern` and those which aren't.

Comment (virgil-serbanuta) [reply kore/test/Test/Kore/Strategies/AllPath/AllPath.hs]: Ok, maybe duplicating the function is not so bad, but here are some suggestions, would any of them be better? 

* implement `ToRulePattern` with an `error` if it's possible somehow to make it trigger only when actually logging.
* implement `ToRulePattern` with something trivial like `\top => \top`
* put the logging functions themselves in a class (in the Goal? a new one?) - I don't like this one that much, really, but it may work.

Comment (ana-pantilie) [reply kore/test/Test/Kore/Strategies/AllPath/AllPath.hs]: I think your second suggestion would be the best solution if we didn't want two `transitionRuleTemplate`. Maybe @ttuegel also has an opinion on this?

File: kore/src/Kore/Logger/DebugProofState.hs [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+    )
+import Kore.Strategies.ProofState
+    ( Prim (..)
+    , ProofState (..)
+    )
+
+data DebugProofState =
+    DebugProofState
+        { configuration :: !TransitionState
+        , transition :: !(Prim (RulePattern Variable))
```
Comment (ttuegel) [inline kore/src/Kore/Logger/DebugProofState.hs]: Why `RulePattern` instead of `ReachabilityRule`?

File: kore/src/Kore/Strategies/Goal.hs [hunk 3]
```diff
@@ -1077,3 +1096,33 @@ configurationDestinationToRule ruleType configuration rhs =
...
+    => Prim goal ~ ProofState.Prim (Rule goal)
+    => ProofState goal goal
+    -- ^ current configuration
+    -> Prim goal
+    -- ^ transition
+    -> log (ProofState goal goal)
+    -- ^ action to be computed
+    -> log (ProofState goal goal)
+debugProofStateBracket
+    (fmap toRulePattern -> config)
```
Comment (ttuegel) [inline kore/src/Kore/Strategies/Goal.hs]: I think we should call this `proofState` instead of `config`.

File: kore/src/Kore/Strategies/Goal.hs [hunk 4]
```diff
@@ -1077,3 +1096,33 @@ configurationDestinationToRule ruleType configuration rhs =
...
+    (fmap toRulePattern -> transition)
+    action
+  = do
+    logM DebugProofState
+        { configuration = Before config
+        , transition
+        }
+    result <- action
+    logM DebugProofState
```
Comment (ttuegel) [inline kore/src/Kore/Strategies/Goal.hs]: We never log an `After` without a `Before`, right? I think the log would be more useful if we logged the initial and final proof states together. Otherwise, I don't think there is an easy way to associate them with each other. Could we change the entry type to be `DebugProofState { initialProofState, finalProofState, transition }`?

File: kore/src/Kore/Logger/DebugProofState.hs [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+    , RewriteRule (..)
+    )
+import Kore.Strategies.ProofState
+    ( Prim (..)
+    , ProofState (..)
+    )
+
+data DebugProofState =
+    DebugProofState
+        { proofstate :: !(ProofState (ReachabilityRule Variable))
```
Comment (ttuegel) [inline kore/src/Kore/Logger/DebugProofState.hs]:
```suggestion
        { proofState :: !(ProofState (ReachabilityRule Variable))
```

File: kore/test/Test/Kore/Strategies/AllPath/AllPath.hs (hunk 1 above)
Comment (ttuegel) [reply kore/test/Test/Kore/Strategies/AllPath/AllPath.hs]: My suggestion would be: instead of modifying the existing `transitionRuleTemplate` to implement logging, implement a function that adds logging to the existing `transitionRuleTemplate`. That is:

```.hs
-- I'm listing this for brevity, but it's not necessary for you to add this type synonym
type TransitionRule monad goal =
        Prim goal
    ->  ProofState goal goal
    ->  TransitionT (Rule goal) monad (ProofState goal goal)

-- existing function:
transitionRuleTemplate :: TransitionRuleTemplate monad goal -> TransitionRule monad goal

-- new function:
withDebugProofState 
    :: MonadLog monad
    => ToRulePattern goal
    => TransitionRule monad goal
    -> TransitionRule monad goal
withDebugProofState = _
-- might need a better name
```

If I understand correctly, we could then use the same `transitionRuleTemplate` in the tests as in the prover, right?

File: kore/src/Kore/Logger/DebugProofState.hs (hunk 5 above)
Comment (ana-pantilie) [reply kore/src/Kore/Logger/DebugProofState.hs]: It would clash with https://github.com/kframework/kore/blob/d09b5e74e0a87ba613a7ce786618f6dcfa81b801/kore/src/Kore/Strategies/ProofState.hs#L106

Comment (virgil-serbanuta) [reply kore/src/Kore/Logger/DebugProofState.hs]: Where? I.e. are you talking about a specific clash, or about the fact that the clash could occur? Usually qualified imports for record fields (as recommended by our coding standards) or importing only what's needed are enough to solve this issue, but it may not work in all cases.

Comment (ana-pantilie) [reply kore/src/Kore/Logger/DebugProofState.hs]: Hmm yes, you're right, sorry. I was just thinking it might be confusing to have two things named `proofState` which are both related to the same type, but after thinking about this a bit more `proofstate` might be more error-prone.

File: kore/src/Kore/Logger/DebugProofState.hs [hunk 6]
```diff
@@ -0,0 +1,53 @@
+{- |
+Copyright   : (c) Runtime Verification, 2019
```
Comment (virgil-serbanuta) [inline kore/src/Kore/Logger/DebugProofState.hs]: 2020?

File: kore/src/Kore/Logger/Output.hs [hunk 7]
```diff
@@ -223,20 +229,26 @@ runLoggerT :: KoreLogOptions -> LoggerT IO a -> IO a
 runLoggerT options loggerT = do
     let runLogger = runReaderT . getLoggerT $ loggerT
     withLogger options $ \logger -> do
-        modifiedLogger <- concurrentLogger logger
-        runLogger modifiedLogger
+        (asyncThread, modifiedLogger) <- concurrentLogger logger
+        result <- runLogger modifiedLogger
+        wait asyncThread
```
Comment (ttuegel) [inline kore/src/Kore/Logger/Output.hs]: We should use [`finally`](https://hackage.haskell.org/package/exceptions-0.10.4/docs/Control-Monad-Catch.html#v:finally) so that if `runLogger modifiedLogger` throws an exception, the logging thread gets a chance to finish writing.
